## Student Attendance Analytics with Pandas

In [1]:
import pandas as pd
import numpy as np

#### Section 0: Data Loading

In [2]:
df = pd.read_excel("csec_attendance.xlsx")
df

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-07,1
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17%,Critical,28 more,2026-09-25,3
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83%,Warning,✓ Met,2026-10-07,1
...,...,...,...,...,...,...,...,...,...,...,...,...
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,58%,Critical,8 more,2026-10-09,0
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67%,Critical,4 more,2026-10-07,1
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8%,Critical,32 more,2026-09-04,10
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8%,Critical,32 more,2026-09-04,10
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0%,Critical,36 more,Never,12

#### Section 1: Data Inspection

In [3]:
"""Q1. Display the first 10 rows, the shape of the DataFrame, and the data types of each column."""
#-----------------------------Write Solution Code-----------------------------
display(df.head(10))
print(df.shape)
print(df.dtypes)

,Roll No,Student Name,Subject,Total Classes,Present,Absent,Excused,Attendance %,Status,Classes Needed (75%),Last Present Date,Consecutive Absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-07,1
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17%,Critical,28 more,2026-09-25,3
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83%,Warning,✓ Met,2026-10-07,1
5,4MW24CS128,SAMRUDDI,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
6,4MW24CS130,SANEEYA ALKIN RIZA,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-09,0
7,4MW24CS131,SANJANA,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
8,4MW24CS132,SANYA,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
9,4MW24CS133,SARGAM,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0,25%,Critical,24 more,2026-09-25,3

(65, 12)
Roll No                   str
Student Name              str
Subject                   str
Total Classes           int64
Present                 int64
Absent                  int64
Excused                 int64
Attendance %              str
Status                    str
Classes Needed (75%)      str
Last Present Date         str
Consecutive Absences    int64
dtype: object

In [4]:
"""Q2. Check for missing values in each column. Identify which columns have null values (especially Last Present Date with "Never") and report the count. """
#-----------------------------Write Solution Code-----------------------------
print(df.isnull().sum())

Roll No                 0
Student Name            0
Subject                 0
Total Classes           0
Present                 0
Absent                  0
Excused                 0
Attendance %            0
Status                  0
Classes Needed (75%)    0
Last Present Date       0
Consecutive Absences    0
dtype: int64

In [5]:
"""Q3. Rename the columns to snake_case (e.g., Roll No → roll_no, Student Name → student_name, Attendance % → attendance_pct). Display the updated column list."""
#-----------------------------Write Solution Code-----------------------------
df.columns = ['roll_no', 'student_name', 'subject', 'total_classes', 'present', 'absent', 'excused', 'attendance_pct', 'status', 'classes_needed_75', 'last_present_date', 'consecutive_absences']
df.head()

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100%,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92%,Safe,✓ Met,2026-10-07,1
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17%,Critical,28 more,2026-09-25,3
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75%,Warning,✓ Met,2026-10-09,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83%,Warning,✓ Met,2026-10-07,1

In [6]:
"""Q4. Convert Attendance % from string format (e.g., "64%") to a numeric float column (0.64 or 64.0). Also convert Last Present Date to datetime, handling "Never" as NaT."""
#-----------------------------Write Solution Code-----------------------------
df['attendance_pct'] = df['attendance_pct'].astype(str).str.rstrip('%').astype(float)
df['last_present_date'] = pd.to_datetime(df['last_present_date'], errors='coerce')
df.head()

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences
0,4MW24CS123,SAKSHI SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,12,0,0,100.0,Safe,✓ Met,2026-10-09,0
1,4MW24CS124,SAMEEKSHA BEKAL,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-07,1
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-25,3
3,4MW24CS126,SAMHITA S RAO,Data Science & GenAI - 3nd Yr - CSE - C,12,9,3,0,75.0,Warning,✓ Met,2026-10-09,0
4,4MW24CS127,SAMIKSHA,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83.0,Warning,✓ Met,2026-10-07,1

#### Section 2: Filtering & Selection

In [7]:
"""Q5. Filter and display all students whose Status is "Critical". Sort them by Attendance % in ascending order."""
#-----------------------------Write Solution Code-----------------------------
df[df['status'] == 'Critical'].sort_values(by='attendance_pct')

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences
20,4MW24CS144,SHREEHARI SHENOY R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
43,4MW24CS167,SURAJ R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
45,4MW24CS169,SUSHAN S POOJARY,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10
53,4MW24CS177,UTHSAV N SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-09,9
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-25,3
9,4MW24CS133,SARGAM,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0,25.0,Critical,24 more,2026-09-25,3
22,4MW24CS146,SHREESHESHA G A,Data Science & GenAI - 3nd Yr - CSE - C,12,4,8,0,33.0,Critical,20 more,2026-10-07,1
41,4MW24CS165,SUNIL BHAT,Data Science & GenAI - 3nd Yr - CSE - C,11,5,6,0,45.0,Critical,13 more,2026-10-07,1
15,4MW24CS139,SHLOAG MAHESH BANT,Data Science & GenAI - 3nd Yr - CSE - C,12,6,6,0,50.0,Critical,12 more,2026-10-07,1
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,58.0,Critical,8 more,2026-10-09,0
30,4MW24CS154,SHREYAS SATISH BHAT,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
11,4MW24CS135,SATHWIK G KAMATH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-07,1
17,4MW24CS141,SHRAVAN,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-07,1
58,4MW24CS182,VISHNU PRASAD,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
51,4MW24CS175,THEJAS B K,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-09-25,3
46,4MW24CS170,SUSHANTH (SEETHARAMA ACHAR),Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
34,4MW24CS158,SINDHU,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-07,1

In [8]:
"""Q6. Extract all students who have 0 present days (fully absent). List their roll numbers, names, and consecutive absences."""
#-----------------------------Write Solution Code-----------------------------
df[df['status'] == 'Critical'].sort_values(by='attendance_pct')

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences
20,4MW24CS144,SHREEHARI SHENOY R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
43,4MW24CS167,SURAJ R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12
45,4MW24CS169,SUSHAN S POOJARY,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10
53,4MW24CS177,UTHSAV N SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-09,9
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-25,3
9,4MW24CS133,SARGAM,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0,25.0,Critical,24 more,2026-09-25,3
22,4MW24CS146,SHREESHESHA G A,Data Science & GenAI - 3nd Yr - CSE - C,12,4,8,0,33.0,Critical,20 more,2026-10-07,1
41,4MW24CS165,SUNIL BHAT,Data Science & GenAI - 3nd Yr - CSE - C,11,5,6,0,45.0,Critical,13 more,2026-10-07,1
15,4MW24CS139,SHLOAG MAHESH BANT,Data Science & GenAI - 3nd Yr - CSE - C,12,6,6,0,50.0,Critical,12 more,2026-10-07,1
60,4MW24CS900,RIYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,7,5,0,58.0,Critical,8 more,2026-10-09,0
30,4MW24CS154,SHREYAS SATISH BHAT,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
11,4MW24CS135,SATHWIK G KAMATH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-07,1
17,4MW24CS141,SHRAVAN,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-07,1
58,4MW24CS182,VISHNU PRASAD,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
51,4MW24CS175,THEJAS B K,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-09-25,3
46,4MW24CS170,SUSHANTH (SEETHARAMA ACHAR),Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
34,4MW24CS158,SINDHU,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0
61,4MW25CS401,ANIRUDH,Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-07,1

In [9]:
"""Q7. Using .loc and .iloc, display:
(a) All "Safe" students using .loc
(b) The first 15 rows and columns 2-6 using .iloc """
#-----------------------------Write Solution Code-----------------------------
df.loc[df['present'] == 0, ['roll_no', 'student_name', 'consecutive_absences']]

       roll_no        student_name  consecutive_absences
20  4MW24CS144  SHREEHARI SHENOY R                    12
43  4MW24CS167             SURAJ R                    12
64  4MW25CS409            YASHVITH                    12

In [10]:
"""Q8. Find all students whose Consecutive Absences is greater than or equal to 5. Display their name, status, and last present date."""
#-----------------------------Write Solution Code-----------------------------
df.loc[df['consecutive_absences'] >= 5, ['student_name', 'status', 'last_present_date']]

          student_name    status last_present_date
20  SHREEHARI SHENOY R  Critical               NaT
43             SURAJ R  Critical               NaT
45    SUSHAN S POOJARY  Critical        2026-09-04
53     UTHSAV N SHETTY  Critical        2026-09-09
62   SANATH S DEVADIGA  Critical        2026-09-04
63            SUSHANTH  Critical        2026-09-04
64            YASHVITH  Critical               NaT

### Section 3: Grouping & Aggregation

In [11]:
"""Q9. Group the data by Status and compute: 
a) Count of students 
b) Average attendance %  
c) Maximum consecutive absences"""
#-----------------------------Write Solution Code-----------------------------
df.groupby('status').agg(
    student_count=('student_name', 'count'),
    average_attendance=('attendance_pct', 'mean'),
    max_consecutive_absences=('consecutive_absences', 'max')
)

          student_count  average_attendance  max_consecutive_absences
status
Critical             21           38.333333                        12
Safe                 20           94.400000                         1
Warning              24           80.000000                         1

In [12]:
"""Q10. Create a new column Attendance Category:
≥ 90% → "Excellent"
75-89% → "Good"
60-74% → "Average"
< 60% → "Poor"
Then use groupby() to count students in each category."""
#-----------------------------Write Solution Code-----------------------------
df['attendance_category'] = pd.cut(
    df['attendance_pct'],
    bins=[-1, 60, 75, 90, 100],
    labels=['Poor', 'Average', 'Good', 'Excellent'],
    right=False
)
df['attendance_category'].value_counts()

attendance_category
Good         24
Excellent    14
Poor         13
Average       8
Name: count, dtype: int64

In [13]:
"""Q11. Calculate the total number of classes conducted (sum of Total Classes) and the total present/absent counts across all students using .agg()."""
#-----------------------------Write Solution Code-----------------------------
df.agg({
    'total_classes': 'sum',
    'present': 'sum',
    'absent': 'sum'
})

total_classes    779
present          553
absent           226
dtype: int64

In [14]:
"""Q12. Group by Status and use .agg() to find:
a)min, max, and mean of Present
b)sum of Absent"""
#-----------------------------Write Solution Code-----------------------------
df.agg({
    'total_classes': 'sum',
    'present': 'sum',
    'absent': 'sum'
})

total_classes    779
present          553
absent           226
dtype: int64

### Section 4: Feature Engineering & Transformation

In [15]:
"""Q13. Create a new column Risk Score using the formula:
Risk Score = (Absent * 0.4) + (Consecutive Absences * 0.6)
Display the top 10 students with the highest risk score."""
#-----------------------------Write Solution Code-----------------------------
df.groupby('status').agg({
    'present': ['min', 'max', 'mean'],
    'absent': 'sum'
})

         present                absent
             min max       mean    sum
status
Critical       0   8   4.571429    155
Safe          11  12  11.300000     14
Warning        9  10   9.625000     57

In [16]:
"""Q14. Add a column Classes Needed (Numeric) by extracting the numeric value from the Classes Needed (75%) column (e.g., "5 more" → 5, "✓ Met" → 0)."""
#-----------------------------Write Solution Code-----------------------------
df['risk_score'] = (df['absent'] * 0.4) + (df['consecutive_absences'] * 0.6)
df.nlargest(10, 'risk_score')

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences,attendance_category,risk_score
20,4MW24CS144,SHREEHARI SHENOY R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0
43,4MW24CS167,SURAJ R,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0
64,4MW25CS409,YASHVITH,Data Science & GenAI - 3nd Yr - CSE - C,12,0,12,0,0.0,Critical,36 more,NaT,12,Poor,12.0
45,4MW24CS169,SUSHAN S POOJARY,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10,Poor,10.4
62,4MW25CS407,SANATH S DEVADIGA,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10,Poor,10.4
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10,Poor,10.4
53,4MW24CS177,UTHSAV N SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-09,9,Poor,9.4
2,4MW24CS125,SAMEER ACHARYA,Data Science & GenAI - 3nd Yr - CSE - C,12,2,10,0,17.0,Critical,28 more,2026-09-25,3,Poor,5.8
9,4MW24CS133,SARGAM,Data Science & GenAI - 3nd Yr - CSE - C,12,3,9,0,25.0,Critical,24 more,2026-09-25,3,Poor,5.4
22,4MW24CS146,SHREESHESHA G A,Data Science & GenAI - 3nd Yr - CSE - C,12,4,8,0,33.0,Critical,20 more,2026-10-07,1,Poor,3.8

In [17]:
"""Q15. Using apply() with a lambda function, create a column Attendance Flag that returns:
a)"Defaulter" if attendance < 75%
b)"Safe" otherwise """
#-----------------------------Write Solution Code-----------------------------
df['classes_needed_numeric'] = df['classes_needed_75'].str.extract(r'(\d+)').fillna(0).astype(int)
df[['student_name', 'classes_needed_numeric']].head()

      student_name  classes_needed_numeric
0    SAKSHI SHETTY                       0
1  SAMEEKSHA BEKAL                       0
2   SAMEER ACHARYA                      28
3    SAMHITA S RAO                       0
4         SAMIKSHA                       0

In [28]:
"""Q16. Use pd.cut() to bin students into attendance ranges: [0-50, 50-75, 75-90, 90-100] and label them as ["Critical", "Warning", "Good", "Excellent"]."""
#-----------------------------Write Solution Code-----------------------------
df['attendance_category'] = pd.cut(
    df['attendance_pct'],
    bins=[0, 50, 75, 90, 100],
    labels=['Critical', 'Warning', 'Good', 'Excellent'],
    include_lowest=True
)

### Section 5: Advanced Analysis

In [24]:
"""Q17. Using pivot_table(), create a summary showing the count of students by Status and Attendance Category (created in Q10)."""
#-----------------------------Write Solution Code-----------------------------
pd.pivot_table(df, index='status', columns='attendance_category', values='student_name', aggfunc='count', fill_value=0)

attendance_category  Critical  Warning  Good  Excellent
status
Critical                   12        9     0          0
Safe                        0        0     0         20
Warning                     0        9    15          0

In [25]:
"""Q18. Identify duplicate student names (e.g., "ANANYA", "DISHA") and display all rows where the base name repeats. Use string manipulation to extract the base name."""
#-----------------------------Write Solution Code-----------------------------
df['base_name'] = df['student_name'].str.split().str[0]
df[df['base_name'].duplicated(keep=False)].sort_values('base_name')

,roll_no,student_name,subject,total_classes,present,absent,excused,attendance_pct,status,classes_needed_75,last_present_date,consecutive_absences,attendance_category,risk_score,classes_needed_numeric,base_name
23,4MW24CS147,SHREYA (JAYANTH ),Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,SHREYA
26,4MW24CS150,SHREYA (VIJAYENDRA),Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,SHREYA
27,4MW24CS151,SHREYA K,Data Science & GenAI - 3nd Yr - CSE - C,12,10,2,0,83.0,Warning,✓ Met,2026-10-09,0,Good,0.8,0,SHREYA
28,4MW24CS152,SHREYA PRABHU,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,SHREYA
29,4MW24CS153,SHREYA SHETTY,Data Science & GenAI - 3nd Yr - CSE - C,12,11,1,0,92.0,Safe,✓ Met,2026-10-09,0,Excellent,0.4,0,SHREYA
46,4MW24CS170,SUSHANTH (SEETHARAMA ACHAR),Data Science & GenAI - 3nd Yr - CSE - C,12,8,4,0,67.0,Critical,4 more,2026-10-09,0,Warning,1.6,4,SUSHANTH
63,4MW25CS408,SUSHANTH,Data Science & GenAI - 3nd Yr - CSE - C,12,1,11,0,8.0,Critical,32 more,2026-09-04,10,Critical,10.4,32,SUSHANTH

In [30]:
""""Q19. Merge this dataset with a hypothetical Student_Details DataFrame containing Roll No, Branch, and Semester. Perform an inner join and display the merged result."""
#-----------------------------Write Solution Code-----------------------------
df[df['status'] == 'Critical'].to_csv('critical_students.csv', index=False)

df.groupby('status').agg({
    'attendance_pct': ['mean', 'min', 'max'],
    'present': 'sum',
    'absent': 'sum'
}).to_csv('status_summary.csv')

df.nlargest(10, 'risk_score').to_csv('top_10_risk_students.csv', index=False)

In [31]:
"""Q20. Export the following to separate CSV files:
(a) All "Critical" students
(b) Summary statistics grouped by Status
(c) Top 10 students by Risk Score"""
#-----------------------------Write Solution Code-----------------------------
df[df['status'] == 'Critical'].to_csv('critical_students.csv', index=False)

df.groupby('status').agg({
    'attendance_pct': ['mean', 'min', 'max'],
    'present': 'sum',
    'absent': 'sum'
}).to_csv('status_summary.csv')

df.nlargest(10, 'risk_score').to_csv('top_10_risk_students.csv', index=False)